# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class License(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, dig_allowed=None, dig_used=None):  # noqa: E501
        """License - a model defined in OpenAPI

        :param id: The id of this License.  # noqa: E501
        :type id: int
        :param dig_allowed: The dig_allowed of this License.  # noqa: E501
        :type dig_allowed: int
        :param dig_used: The dig_used of this License.  # noqa: E501
        :type dig_used: int
        """
        self.openapi_types = {
            'id': int,
            'dig_allowed': int,
            'dig_used': int
        }

        self.attribute_map = {
            'id': 'id',
            'dig_allowed': 'digAllowed',
            'dig_used': 'digUsed'
        }

        self._id = id
        self._dig_allowed = dig_allowed
        self._dig_used = dig_used

    @classmethod
    def from_dict(cls, dikt) -> 'License':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The license of this License.  # noqa: E501
        :rtype: License
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this License.


        :return: The id of this License.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this License.


        :param id: The id of this License.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def dig_allowed(self):
        """Gets the dig_allowed of this License.

        Non-negative amount of treasures/etc.  # noqa: E501

        :return: The dig_allowed of this License.
        :rtype: int
        """
        return self._dig_allowed

    @dig_allowed.setter
    def dig_allowed(self, dig_allowed):
        """Sets the dig_allowed of this License.

        Non-negative amount of treasures/etc.  # noqa: E501

        :param dig_allowed: The dig_allowed of this License.
        :type dig_allowed: int
        """
        if dig_allowed is None:
            raise ValueError("Invalid value for `dig_allowed`, must not be `None`")  # noqa: E501
        if dig_allowed is not None and dig_allowed < 0:  # noqa: E501
            raise ValueError("Invalid value for `dig_allowed`, must be a value greater than or equal to `0`")  # noqa: E501

        self._dig_allowed = dig_allowed

    @property
    def dig_used(self):
        """Gets the dig_used of this License.

        Non-negative amount of treasures/etc.  # noqa: E501

        :return: The dig_used of this License.
        :rtype: int
        """
        return self._dig_used

    @dig_used.setter
    def dig_used(self, dig_used):
        """Sets the dig_used of this License.

        Non-negative amount of treasures/etc.  # noqa: E501

        :param dig_used: The dig_used of this License.
        :type dig_used: int
        """
        if dig_used is None:
            raise ValueError("Invalid value for `dig_used`, must not be `None`")  # noqa: E501
        if dig_used is not None and dig_used < 0:  # noqa: E501
            raise ValueError("Invalid value for `dig_used`, must be a value greater than or equal to `0`")  # noqa: E501

        self._dig_used = dig_used
